swagger: '2.0'
info:
  title: API
  version: '1.0'
basePath: /
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /user:
    get:
      tags:
        - User
      summary: Retrieves the collection of User resources.
      responses:
        '200':
          description: User collection response
          schema:
            $ref: '#/definitions/User'
      description: dsdád
definitions:
  User:
    required:
      - username
      - email
    properties:
      id:
        type: integer
      email:
        type: string
      username:
        type: string
tags:
  - name: oke